### ISSUE TITLE
micro:bit版が欲しい

### ISSUE THREAD

**Issue by satakagi** [chirimen-oh/chirimen-TY51822r3#4]
単なる願望ですが・・

**Comment by dynamis** [comment]
BLE経由での通信で指示する方式を仕様化して、それをどちらのデバイスでも、あるいは今後他のBLE経由でGPIOなど使えるデバイスで受け側のファームさえ用意すれば動かせるようにしたい話になりますね。

リモートWebGPIOの通信プロトコル定義みたいな。

**Comment by dynamis** [comment]
既に開発が始まっているので assign しました＆別リポジトリでの開発になっているのでこちらのリポジトリに issue は不要と判断してクローズします:

https://github.com/chirimen-oh/webGPIO-etc-on-microbit-via-webBluetooth
